import = ["~/.config/alacritty/themes/one_dark.toml"]

[window]
opacity = 0.8
dynamic_padding = false

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true

[font]
size = 11.0
offset.x = 0
offset.y = 0

[font.normal]
family = "Noto Mono"
style = "Regular"
[font.bold]
family = "Noto Mono"
style = "Bold"
[font.italic]
family = "Noto Mono"
style = "Italic"

