[window]
opacity = 0.8
dynamic_padding = false

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true

[font]
size = 9.0
offset.x = 0
offset.y = 0

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[general]
import = ["~/.config/alacritty/themes/one_dark.toml"]

