import = ["~/.config/alacritty/themes/monokai_charcoal.toml",]

[window]
opacity = 1.0

[window.padding]
x = 16
y = 16

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"
